creating ecommerce management application
netabirami/FinalProject pull request #1
Opened 2024-01-08 21:31 UTC by netabirami

2024-01-11 09:10 UTC, f4r33 commented on pom.xml
> +<!--		<dependency>-->
Remove comments

2024-01-11 09:11 UTC, f4r33 commented on src/main/java/com/zalando/ECommerceManagement/userManagement/controller/UserController.java
> +public class UserController {
Can you please format the code for this class by clicking ⌘⌥L (macOS) / Ctrl+Alt+L (Windows/Linux

2024-01-11 09:11 UTC, f4r33 commented on src/main/java/com/zalando/ECommerceManagement/userManagement/controller/UserController.java
> +//       String encodedPassword = new BCryptPasswordEncoder().encode(user.getPassword());
Remove comments

2024-01-11 09:11 UTC, f4r33 commented on src/main/java/com/zalando/ECommerceManagement/userManagement/controller/UserController.java
> +    public User addUser ( @Valid  @RequestBody User user){
formatting

2024-01-11 09:12 UTC, f4r33 commented on src/main/java/com/zalando/ECommerceManagement/userManagement/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User,Integer> {
add space after `<User,`

2024-01-11 09:13 UTC, f4r33 commented on src/main/java/com/zalando/ECommerceManagement/userManagement/service/UserService.java
> +    @Autowired
use constructor autowiring

2024-01-11 09:13 UTC, f4r33 commented on src/main/java/com/zalando/ECommerceManagement/userManagement/service/UserService.java
> +
extra space

2024-01-11 09:13 UTC, f4r33 commented on src/main/java/com/zalando/ECommerceManagement/userManagement/service/UserService.java
> +
extra space

2024-01-11 09:20 UTC, f4r33 commented on src/main/java/com/zalando/ECommerceManagement/userManagement/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler({InvalidMethodArgumentException.class})
add empty line before this

2024-01-11 09:21 UTC, f4r33 commented on src/main/java/com/zalando/ECommerceManagement/userManagement/exception/InvalidMethodArgumentException.java
> +@AllArgsConstructor
Do you need both `@AllArgsConstructor` and `@NoArgsConstructor`?

2024-01-11 09:26 UTC, f4r33 commented on src/test/java/com/zalando/ECommerceManagement/userManagement/controller/UserControllerTest.java
> +    static Stream<Arguments> getUserInput() {
we can make this private

2024-01-11 09:26 UTC, f4r33 requested changes
Address the comments please 😄

2024-01-11 09:31 UTC, f4r33 commented
In the future when you create a PR can you create links to the ticket in Jira, please? Also, the name for the branch should be more descriptive. Ideally, we should have one branch per ticket and following the naming convention [ticket-id]-short-name. So for example, for [this ticket](https://zalando-abirami-project.atlassian.net/jira/software/projects/SCRUM/boards/1?selectedIssue=SCRUM-13) the name would be SCRUM-13-user-api

2024-01-12 08:28 UTC, faruka-startsteps commented on pom.xml
> +<!--		<dependency>-->
still not removed

2024-01-12 08:29 UTC, faruka-startsteps commented on src/main/java/com/zalando/ECommerceManagement/userManagement/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler({InvalidMethodArgumentException.class})
still no empty line

2024-01-12 08:47 UTC, merged